aircraft_features = {
    "220": {
        "type": "narrowbody",
        "size": "small",
        "engine": "jet",
        "is_russia": False,
        "model": "A220",
        "seating_class": "small",
        "range_class": "short",
    },
    "767": {
        "type": "widebody",
        "size": "large",
        "engine": "jet",
        "is_russia": False,
        "model": "B767",
        "seating_class": "large",
        "range_class": "long",
    },
    "763": {
        "type": "widebody",
        "size": "large",
        "engine": "jet",
        "is_russia": False,
        "model": "B767-300",
        "seating_class": "large",
        "range_class": "long",
    },
    "E75": {
        "type": "regional",
        "size": "small",
        "engine": "jet",
        "is_russia": False,
        "model": "E175",
        "seating_class": "small",
        "range_class": "short",
    },
    "753": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": False,
        "model": "B757-300",
        "seating_class": "medium",
        "range_class": "medium",
    },
    "764": {
        "type": "widebody",
        "size": "large",
        "engine": "jet",
        "is_russia": False,
        "model": "B767-400",
        "seating_class": "large",
        "range_class": "long",
    },
    "747": {
        "type": "widebody",
        "size": "large",
        "engine": "jet",
        "is_russia": False,
        "model": "B747",
        "seating_class": "large",
        "range_class": "long",
    },
    "ERD": {
        "type": "regional",
        "size": "small",
        "engine": "jet",
        "is_russia": True,
        "model": "ERJ family",
        "seating_class": "small",
        "range_class": "short",
    },
    "733": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": False,
        "model": "B737-300",
        "seating_class": "medium",
        "range_class": "short",
    },
    "E70": {
        "type": "regional",
        "size": "small",
        "engine": "jet",
        "is_russia": False,
        "model": "E170",
        "seating_class": "small",
        "range_class": "short",
    },
    "290": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": True,
        "model": "MC-21",
        "seating_class": "medium",
        "range_class": "short",
    },
    "74H": {
        "type": "widebody",
        "size": "large",
        "engine": "jet",
        "is_russia": False,
        "model": "B747-8",
        "seating_class": "large",
        "range_class": "long",
    },
    "E95": {
        "type": "regional",
        "size": "small",
        "engine": "jet",
        "is_russia": False,
        "model": "E195",
        "seating_class": "small",
        "range_class": "short",
    },
    "73G": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": False,
        "model": "B737-700",
        "seating_class": "medium",
        "range_class": "short",
    },
    "787": {
        "type": "widebody",
        "size": "large",
        "engine": "jet",
        "is_russia": False,
        "model": "B787",
        "seating_class": "large",
        "range_class": "long",
    },
    "TBA": {
        "type": "unknown",
        "size": "unknown",
        "engine": "unknown",
        "is_russia": False,
        "model": "unknown",
        "seating_class": "unknown",
        "range_class": "unknown",
    },
    "33H": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": False,
        "model": "A330",
        "seating_class": "medium",
        "range_class": "long",
    },
    "789": {
        "type": "widebody",
        "size": "large",
        "engine": "jet",
        "is_russia": False,
        "model": "B787-9",
        "seating_class": "large",
        "range_class": "long",
    },
    "739": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": False,
        "model": "B737-900",
        "seating_class": "medium",
        "range_class": "short",
    },
    "32Щ": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": True,
        "model": "A320 (Russian)",
        "seating_class": "medium",
        "range_class": "short",
    },
    "32S": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": False,
        "model": "A320 family",
        "seating_class": "medium",
        "range_class": "short",
    },
    "325": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": True,
        "model": "MC-21 variant",
        "seating_class": "medium",
        "range_class": "short",
    },
    "77W": {
        "type": "widebody",
        "size": "large",
        "engine": "jet",
        "is_russia": False,
        "model": "B777-300ER",
        "seating_class": "large",
        "range_class": "long",
    },
    "77В": {
        "type": "widebody",
        "size": "large",
        "engine": "jet",
        "is_russia": True,
        "model": "B777 (Russian)",
        "seating_class": "large",
        "range_class": "long",
    },
    "SU9": {
        "type": "regional",
        "size": "small",
        "engine": "jet",
        "is_russia": True,
        "model": "SSJ100",
        "seating_class": "small",
        "range_class": "short",
    },
    "YK2": {
        "type": "regional",
        "size": "small",
        "engine": "jet",
        "is_russia": True,
        "model": "Yak-42",
        "seating_class": "small",
        "range_class": "short",
    },
    "319": {
        "type": "narrowbody",
        "size": "small",
        "engine": "jet",
        "is_russia": False,
        "model": "A319",
        "seating_class": "small",
        "range_class": "short",
    },
    "32B": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": False,
        "model": "A320 family",
        "seating_class": "medium",
        "range_class": "short",
    },
    "380": {
        "type": "widebody",
        "size": "large",
        "engine": "jet",
        "is_russia": False,
        "model": "A380",
        "seating_class": "large",
        "range_class": "long",
    },
    "DH8": {
        "type": "regional",
        "size": "small",
        "engine": "turboprop",
        "is_russia": False,
        "model": "DHC-8",
        "seating_class": "small",
        "range_class": "short",
    },
    "339": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": False,
        "model": "B737-900",
        "seating_class": "medium",
        "range_class": "short",
    },
    "CRK": {
        "type": "regional",
        "size": "small",
        "engine": "jet",
        "is_russia": True,
        "model": "CRK variant",
        "seating_class": "small",
        "range_class": "short",
    },
    "788": {
        "type": "widebody",
        "size": "large",
        "engine": "jet",
        "is_russia": False,
        "model": "B787-8",
        "seating_class": "large",
        "range_class": "long",
    },
    "31N": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": False,
        "model": "A310 variant",
        "seating_class": "medium",
        "range_class": "medium",
    },
    "338": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": False,
        "model": "B737-800",
        "seating_class": "medium",
        "range_class": "short",
    },
    "BUS": {
        "type": "unknown",
        "size": "unknown",
        "engine": "unknown",
        "is_russia": False,
        "model": "unknown",
        "seating_class": "unknown",
        "range_class": "unknown",
    },
    "919": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": False,
        "model": "B737 MAX 9",
        "seating_class": "medium",
        "range_class": "short",
    },
    "32M": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": True,
        "model": "A320 (Russian)",
        "seating_class": "medium",
        "range_class": "short",
    },
    "T20": {
        "type": "unknown",
        "size": "unknown",
        "engine": "unknown",
        "is_russia": False,
        "model": "unknown",
        "seating_class": "unknown",
        "range_class": "unknown",
    },
    "73E": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": False,
        "model": "B737-700",
        "seating_class": "medium",
        "range_class": "short",
    },
    "736": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": False,
        "model": "B737-600",
        "seating_class": "medium",
        "range_class": "short",
    },
    "76W": {
        "type": "widebody",
        "size": "large",
        "engine": "jet",
        "is_russia": False,
        "model": "B767-300ER",
        "seating_class": "large",
        "range_class": "long",
    },
    "350": {
        "type": "widebody",
        "size": "large",
        "engine": "jet",
        "is_russia": False,
        "model": "A350",
        "seating_class": "large",
        "range_class": "long",
    },
    "32G": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": True,
        "model": "A320 (Russian)",
        "seating_class": "medium",
        "range_class": "short",
    },
    "343": {
        "type": "widebody",
        "size": "large",
        "engine": "jet",
        "is_russia": False,
        "model": "A340",
        "seating_class": "large",
        "range_class": "long",
    },
    "73L": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": False,
        "model": "B737-700",
        "seating_class": "medium",
        "range_class": "short",
    },
    "738": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": False,
        "model": "B737-800",
        "seating_class": "medium",
        "range_class": "short",
    },
    "73C": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": False,
        "model": "B737-600",
        "seating_class": "medium",
        "range_class": "short",
    },
    "AN6": {
        "type": "regional",
        "size": "small",
        "engine": "turboprop",
        "is_russia": True,
        "model": "AN-26/An-24",
        "seating_class": "small",
        "range_class": "short",
    },
    "32Q": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": True,
        "model": "A320 (Russian)",
        "seating_class": "medium",
        "range_class": "short",
    },
    "32N": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": True,
        "model": "A320 (Russian)",
        "seating_class": "medium",
        "range_class": "short",
    },
    "E7W": {
        "type": "regional",
        "size": "small",
        "engine": "jet",
        "is_russia": False,
        "model": "E170 variant",
        "seating_class": "small",
        "range_class": "short",
    },
    "320": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": False,
        "model": "A320",
        "seating_class": "medium",
        "range_class": "short",
    },
    "ATR": {
        "type": "regional",
        "size": "small",
        "engine": "turboprop",
        "is_russia": False,
        "model": "ATR family",
        "seating_class": "small",
        "range_class": "short",
    },
    "DHT": {
        "type": "unknown",
        "size": "unknown",
        "engine": "unknown",
        "is_russia": True,
        "model": "DHT variant",
        "seating_class": "unknown",
        "range_class": "unknown",
    },
    "734": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": False,
        "model": "B737-400",
        "seating_class": "medium",
        "range_class": "short",
    },
    "KZN": {
        "type": "unknown",
        "size": "unknown",
        "engine": "unknown",
        "is_russia": True,
        "model": "KZN variant",
        "seating_class": "unknown",
        "range_class": "unknown",
    },
    "DH4": {
        "type": "regional",
        "size": "small",
        "engine": "turboprop",
        "is_russia": False,
        "model": "DHC-4",
        "seating_class": "small",
        "range_class": "short",
    },
    "L4T": {
        "type": "unknown",
        "size": "unknown",
        "engine": "unknown",
        "is_russia": True,
        "model": "L4T variant",
        "seating_class": "unknown",
        "range_class": "unknown",
    },
    "EMJ": {
        "type": "unknown",
        "size": "unknown",
        "engine": "unknown",
        "is_russia": True,
        "model": "EMJ variant",
        "seating_class": "unknown",
        "range_class": "unknown",
    },
    "32A": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": True,
        "model": "A320 (Russian)",
        "seating_class": "medium",
        "range_class": "short",
    },
    "AT5": {
        "type": "unknown",
        "size": "unknown",
        "engine": "unknown",
        "is_russia": True,
        "model": "AT5 variant",
        "seating_class": "unknown",
        "range_class": "unknown",
    },
    "333": {
        "type": "widebody",
        "size": "large",
        "engine": "jet",
        "is_russia": False,
        "model": "A330-300",
        "seating_class": "large",
        "range_class": "long",
    },
    "73H": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": False,
        "model": "B737-700",
        "seating_class": "medium",
        "range_class": "short",
    },
    "752": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": False,
        "model": "B757-200",
        "seating_class": "medium",
        "range_class": "medium",
    },
    "73R": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": False,
        "model": "B737-800",
        "seating_class": "medium",
        "range_class": "short",
    },
    "762": {
        "type": "widebody",
        "size": "large",
        "engine": "jet",
        "is_russia": False,
        "model": "B767-200",
        "seating_class": "large",
        "range_class": "long",
    },
    "295": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": True,
        "model": "MC-21",
        "seating_class": "medium",
        "range_class": "short",
    },
    "332": {
        "type": "widebody",
        "size": "large",
        "engine": "jet",
        "is_russia": False,
        "model": "A332",
        "seating_class": "large",
        "range_class": "long",
    },
    "77L": {
        "type": "widebody",
        "size": "large",
        "engine": "jet",
        "is_russia": False,
        "model": "B777-200",
        "seating_class": "large",
        "range_class": "long",
    },
    "7S8": {
        "type": "unknown",
        "size": "unknown",
        "engine": "unknown",
        "is_russia": True,
        "model": "7S8 variant",
        "seating_class": "unknown",
        "range_class": "unknown",
    },
    "351": {
        "type": "widebody",
        "size": "large",
        "engine": "jet",
        "is_russia": False,
        "model": "A350-1000",
        "seating_class": "large",
        "range_class": "long",
    },
    "772": {
        "type": "widebody",
        "size": "large",
        "engine": "jet",
        "is_russia": False,
        "model": "B777-200ER",
        "seating_class": "large",
        "range_class": "long",
    },
    "73N": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": False,
        "model": "B737-900",
        "seating_class": "medium",
        "range_class": "short",
    },
    "32L": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": True,
        "model": "A320 (Russian)",
        "seating_class": "medium",
        "range_class": "short",
    },
    "CR2": {
        "type": "regional",
        "size": "small",
        "engine": "jet",
        "is_russia": True,
        "model": "CRJ variant",
        "seating_class": "small",
        "range_class": "short",
    },
    "388": {
        "type": "widebody",
        "size": "large",
        "engine": "jet",
        "is_russia": False,
        "model": "A380-800",
        "seating_class": "large",
        "range_class": "long",
    },
    "TRS": {
        "type": "unknown",
        "size": "unknown",
        "engine": "unknown",
        "is_russia": True,
        "model": "TRS variant",
        "seating_class": "unknown",
        "range_class": "unknown",
    },
    "SUB": {
        "type": "unknown",
        "size": "unknown",
        "engine": "unknown",
        "is_russia": True,
        "model": "SUB variant",
        "seating_class": "unknown",
        "range_class": "unknown",
    },
    "73Q": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": False,
        "model": "B737 variant",
        "seating_class": "medium",
        "range_class": "short",
    },
    "SFA": {
        "type": "unknown",
        "size": "unknown",
        "engine": "unknown",
        "is_russia": True,
        "model": "SFA variant",
        "seating_class": "unknown",
        "range_class": "unknown",
    },
    "773": {
        "type": "widebody",
        "size": "large",
        "engine": "jet",
        "is_russia": False,
        "model": "B777-300",
        "seating_class": "large",
        "range_class": "long",
    },
    "ARJ": {
        "type": "regional",
        "size": "small",
        "engine": "jet",
        "is_russia": False,
        "model": "ARJ21",
        "seating_class": "small",
        "range_class": "short",
    },
    "TRN": {
        "type": "unknown",
        "size": "unknown",
        "engine": "unknown",
        "is_russia": True,
        "model": "TRN variant",
        "seating_class": "unknown",
        "range_class": "unknown",
    },
    "BEH": {
        "type": "unknown",
        "size": "unknown",
        "engine": "unknown",
        "is_russia": True,
        "model": "BEH variant",
        "seating_class": "unknown",
        "range_class": "unknown",
    },
    "73J": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": False,
        "model": "B737 variant",
        "seating_class": "medium",
        "range_class": "short",
    },
    "777": {
        "type": "widebody",
        "size": "large",
        "engine": "jet",
        "is_russia": False,
        "model": "B777",
        "seating_class": "large",
        "range_class": "long",
    },
    "73W": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": False,
        "model": "B737 variant",
        "seating_class": "medium",
        "range_class": "short",
    },
    "781": {
        "type": "widebody",
        "size": "large",
        "engine": "jet",
        "is_russia": False,
        "model": "B787-1 variant",
        "seating_class": "large",
        "range_class": "long",
    },
    "223": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": False,
        "model": "B737 variant",
        "seating_class": "medium",
        "range_class": "short",
    },
    "32Y": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": True,
        "model": "A320 (Russian)",
        "seating_class": "medium",
        "range_class": "short",
    },
    "73M": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": False,
        "model": "B737 variant",
        "seating_class": "medium",
        "range_class": "short",
    },
    "0": {
        "type": "unknown",
        "size": "unknown",
        "engine": "unknown",
        "is_russia": False,
        "model": "unknown",
        "seating_class": "unknown",
        "range_class": "unknown",
    },
    "CR9": {
        "type": "regional",
        "size": "small",
        "engine": "jet",
        "is_russia": True,
        "model": "CRJ variant",
        "seating_class": "small",
        "range_class": "short",
    },
    "7M9": {
        "type": "unknown",
        "size": "unknown",
        "engine": "unknown",
        "is_russia": True,
        "model": "7M9 variant",
        "seating_class": "unknown",
        "range_class": "unknown",
    },
    "318": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": False,
        "model": "A318",
        "seating_class": "small",
        "range_class": "short",
    },
    "7M8": {
        "type": "unknown",
        "size": "unknown",
        "engine": "unknown",
        "is_russia": True,
        "model": "7M8 variant",
        "seating_class": "unknown",
        "range_class": "unknown",
    },
    "321": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": False,
        "model": "A321",
        "seating_class": "medium",
        "range_class": "short",
    },
    "KJA": {
        "type": "unknown",
        "size": "unknown",
        "engine": "unknown",
        "is_russia": True,
        "model": "KJA variant",
        "seating_class": "unknown",
        "range_class": "unknown",
    },
    "346": {
        "type": "widebody",
        "size": "large",
        "engine": "jet",
        "is_russia": False,
        "model": "A346",
        "seating_class": "large",
        "range_class": "long",
    },
    "YK4": {
        "type": "regional",
        "size": "small",
        "engine": "jet",
        "is_russia": True,
        "model": "Yak-42",
        "seating_class": "small",
        "range_class": "short",
    },
    "744": {
        "type": "widebody",
        "size": "large",
        "engine": "jet",
        "is_russia": False,
        "model": "B747-400",
        "seating_class": "large",
        "range_class": "long",
    },
    "CRJ": {
        "type": "regional",
        "size": "small",
        "engine": "jet",
        "is_russia": True,
        "model": "CRJ family",
        "seating_class": "small",
        "range_class": "short",
    },
    "AT7": {
        "type": "unknown",
        "size": "unknown",
        "engine": "unknown",
        "is_russia": True,
        "model": "AT7 variant",
        "seating_class": "unknown",
        "range_class": "unknown",
    },
    "C27": {
        "type": "unknown",
        "size": "unknown",
        "engine": "unknown",
        "is_russia": True,
        "model": "C27 variant",
        "seating_class": "unknown",
        "range_class": "unknown",
    },
    "330": {
        "type": "widebody",
        "size": "large",
        "engine": "jet",
        "is_russia": False,
        "model": "A330-200",
        "seating_class": "large",
        "range_class": "long",
    },
    "E90": {
        "type": "regional",
        "size": "small",
        "engine": "jet",
        "is_russia": False,
        "model": "E190",
        "seating_class": "small",
        "range_class": "short",
    },
    "MRV": {
        "type": "unknown",
        "size": "unknown",
        "engine": "unknown",
        "is_russia": True,
        "model": "MRV variant",
        "seating_class": "unknown",
        "range_class": "unknown",
    },
    "DH3": {
        "type": "regional",
        "size": "small",
        "engine": "turboprop",
        "is_russia": False,
        "model": "DHC-3",
        "seating_class": "small",
        "range_class": "short",
    },
    "MOW": {
        "type": "unknown",
        "size": "unknown",
        "engine": "unknown",
        "is_russia": True,
        "model": "MOW variant",
        "seating_class": "unknown",
        "range_class": "unknown",
    },
    "757": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": False,
        "model": "B757",
        "seating_class": "medium",
        "range_class": "medium",
    },
    "737": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": False,
        "model": "B737",
        "seating_class": "medium",
        "range_class": "short",
    },
    "ER3": {
        "type": "regional",
        "size": "small",
        "engine": "jet",
        "is_russia": True,
        "model": "ERJ variant",
        "seating_class": "small",
        "range_class": "short",
    },
    "735": {
        "type": "narrowbody",
        "size": "medium",
        "engine": "jet",
        "is_russia": False,
        "model": "B737-500",
        "seating_class": "medium",
        "range_class": "short",
    },
    "AN4": {
        "type": "regional",
        "size": "small",
        "engine": "turboprop",
        "is_russia": True,
        "model": "AN-24",
        "seating_class": "small",
        "range_class": "short",
    },
    "359": {
        "type": "widebody",
        "size": "large",
        "engine": "jet",
        "is_russia": False,
        "model": "A350-900",
        "seating_class": "large",
        "range_class": "long",
    },
    "33L": {
        "type": "widebody",
        "size": "large",
        "engine": "jet",
        "is_russia": False,
        "model": "A330-300",
        "seating_class": "large",
        "range_class": "long",
    },
}
